name: mikeway
description: A starting point for Dart libraries or applications.
version: 0.0.1
repository: https://github.com/michael-wang/mikeway

environment:
  sdk: ">=2.19.5 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  equatable: ^2.0.5
  lints: ^2.0.0
  test: ^1.21.0
